language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
    - DEPLOY_VERSION="6.6"
    - SCRIBBLE_ENTRYPOINT_FILE="syntax-warn/main.scrbl"
  matrix:
    - RACKET_VERSION=6.4 RUN_COVER=true
    - RACKET_VERSION=6.5 RUN_COVER=true
    - RACKET_VERSION=6.6
    - RACKET_VERSION=HEAD
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - 'export PATH="${RACKET_DIR}/bin:${PATH}"'
  - if [ -n "$RUN_COVER" ]; then raco pkg install --deps search-auto cover cover-coveralls; fi
install:
  - raco pkg install --auto
      $TRAVIS_BUILD_DIR/syntax-warn
      $TRAVIS_BUILD_DIR/syntax-warn-lang
      $TRAVIS_BUILD_DIR/syntax-warn-test
script:
  - raco test -c warn racket/base
  - if [ -n "$RUN_COVER" ]; then raco cover -f coveralls -d $TRAVIS_BUILD_DIR/coverage -c warn racket/base; fi
after_success:
  - echo "Starting deploy"
  - if [ "${DEPLOY_VERSION}" != "${RACKET_VERSION}" ]; then exit 0; fi
  - if [ "${TRAVIS_BRANCH}" != "master" ]; then exit 0; fi
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then exit 0; fi
  - rm -rf out || exit 0;
  - mkdir out;
  - echo "In out dir"
  - raco scribble +m --dest out --dest-name index --redirect-main "https://docs.racket-lang.org/" ${SCRIBBLE_ENTRYPOINT_FILE}
  - cd out
  - git init
  - git config user.name "Travis CI"
  - git config user.email "jackhfirth@gmail.com"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/jackfirth/syntax-warn.git" master:gh-pages > /dev/null
